name: event_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  built_value: ^8.6.1
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  http: ^1.1.0
  injectable: ^2.2.0
  json_annotation: ^4.8.1
  provider: ^6.0.5
  redux: ^5.0.0
  redux_epics: ^0.15.1
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  injectable_generator: ^2.3.0
  json_serializable: ^6.7.1
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  assets:
    - .private