name: event_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  built_value: ^8.6.1
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_redux: ^0.10.0
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  hive: ^2.2.3
  http: ^1.1.0
  injectable: ^2.2.0
  intl: ^0.18.0 # flutter_localization sdk depends on version 0.18.0
  json_annotation: ^4.8.1
  path: ^1.8.3
  path_provider: ^2.1.0
  provider: ^6.0.5
  redux: ^5.0.0
  redux_epics: ^0.15.1
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  injectable_generator: ^2.3.0
  json_serializable: ^6.7.1
  very_good_analysis: ^5.0.0+1

flutter_intl:
  enabled: true
  arb_dir: assets/l10n

flutter:
  uses-material-design: true
  assets:
    - assets/font/
    - assets/svg/
    - assets/png/
    - .private
  fonts:
    - family: TiemposHeadline
      fonts:
        - asset: assets/font/TiemposHeadline-Regular.otf