name: app - quality-assurance
on:
  push:

jobs:
  quality-assurance:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - name: Fvm config action
        id: fvm-config-action
        uses: kuhnroyal/flutter-fvm-config-action@v1

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}

      - name: Install Dart
        uses: dart-lang/setup-dart@v1

      - name: Config fvm
        run: dart pub global activate fvm

      - name: Install upcode
        run: |
          dart pub global activate upcode_ci
          echo "~/.pub-cache/bin" >> $GITHUB_PATH

      - name: Setup flutter project
        run: |
          upcode flutter:environment set
          flutter pub get

      - name: Analyze flutter package
        run: upcode flutter:analyze

      - name: Check format
        run: upcode flutter:format